services:
  frontend:
    build:
      context: ./frontend
      dockerfile: .dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - postgres
      - backend-go

  backend-go:
    build:
      context: ./backend
      dockerfile: .dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=yapp
      - DB_SSLMODE=disable
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    stop_grace_period: 2s
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  rust-judge:
    build:
      context: ./judge
      dockerfile: .dockerfile
    volumes:
      - ./judge:/judge
      - rust-target:/judge/target
      - /var/run/docker.sock:/var/run/docker.sock
      - shared:/shared
    stop_grace_period: 2s
    depends_on:
      - backend-go

  rust-test:
    build:
      context: ./judge
      dockerfile: .dockerfile
    command: cargo test -- --nocapture
    volumes:
      - ./judge:/judge
      - rust-target:/judge/target
      - /var/run/docker.sock:/var/run/docker.sock
      - shared:/shared
    depends_on:
      - backend-go

  redis:
    image: redis:7-alpine
    volumes:
      - redis-data:/data
    restart: always
    ports:
      - "6379:6379"
    command: redis-server
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:16-alpine
    env_file: ".env"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: yapp
      PGDATA: /data/postgres
    volumes:
      - postgres-data:/data/postgres
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d yapp"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Interface web pour gérer la BDD (dev only)
  adminer:
    image: adminer:latest
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    profiles:
      - dev

volumes:
  redis-data:
  postgres-data:
  rust-target:
  shared:
