services:
  frontend:
    build:
      context: ./frontend
      dockerfile: .dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend-go

  backend-go:
    build:
      context: ./backend
      dockerfile: .dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8080:8080"
    env_file: ".env"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    stop_grace_period: 2s
    depends_on:
      redis:
        condition: service_healthy

  rust-judge:
    build:
      context: ./judge
      dockerfile: .dockerfile
    volumes:
      - ./judge:/judge
      - rust-target:/judge/target
      - /var/run/docker.sock:/var/run/docker.sock
      - shared:/shared
    stop_grace_period: 2s
    depends_on:
      backend-go:
        condition: service_started
      redis:
        condition: service_healthy

  rust-test:
    build:
      context: ./judge
      dockerfile: .dockerfile
    command: cargo test -- --nocapture
    volumes:
      - ./judge:/judge
      - rust-target:/judge/target
      - /var/run/docker.sock:/var/run/docker.sock
      - shared:/shared
    depends_on:
      - backend-go

  redis:
    image: redis:7-alpine
    volumes:
      - redis-data:/data
    restart: always
    ports:
      - "6379:6379"
    command: redis-server
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis-data:
  rust-target:
  shared:
