name: Rust PR Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy, rustfmt
          override: true

      - name: Build
        working-directory: ./judge
        run: cargo check --all --all-targets

      - name: Lint
        working-directory: ./judge
        run: cargo clippy --all-targets -- -D warnings

      - name: Format Check
        working-directory: ./judge
        run: cargo fmt --all -- --check
